add spec of op number
appliedzkp/zkevm-specs pull request #138
Opened 2022-03-04 02:42 UTC by bchyl

2022-03-07 10:15 UTC, ChihChengLiang approved these changes
LGTM

2022-03-07 10:16 UTC, ChihChengLiang requested changes
Oh, sorry a nitpick

2022-03-07 10:16 UTC, ChihChengLiang commented on specs/opcode/43NUMBER.md
> +# Timestamp op code
```suggestion
# Number op code
```

2022-03-07 11:21 UTC, bchyl commented on specs/opcode/43NUMBER.md
> +# Timestamp op code
accept it, 3gs very much.

2022-03-07 13:07 UTC, ChihChengLiang approved these changes
Thanks for the fix!

2022-03-07 13:07 UTC, merged

2022-03-11 14:31 UTC, barryWhiteHat commented
@bchyl thanks for your PR. Do you have some email address or IM we could use for direct communication ?